BTN.EXCEL_UPLOAD = 엑셀업로드
BTN.EXCEL_BATCH_UPLOAD = 엑셀일괄업로드
BTN.EXCEL_OUT_COO_UPLOAD = 원산지확인서 업로드
BTN.EXCEL_OUT_COO_BATCH_UPLOAD = 원산지확인서 일괄업로드
BTN.EXECUTE = 실행
BTN.DOWNLOAD_TEMPLATES = 양식다운로드
BTN.CANCEL = 취소
BTN.SAVE = 저장
BTN.MOVE = 이동
BTN.DELETE = 삭제
BTN.MODIFY = 수정
BTN.PRINT = 인쇄
BTN.SEND_HISTORY = 발송이력
BTN.MODIFY_SUPPLY_INCHARGE = 담당자정보수정
BTN.SEND_EMAIL = 이메일발송
BTN.ADD_FILE = 파일추가
BTN.PREVIEW_EMAIL = 작성메일 미리보기
BTN.EMAIL_SEND = 메일보내기