#Unipass Send/receive Path set
file.xml.dir=C:/Users/KPMG/git/ap-drwb/src/main/webapp/WEB-INF/viewResources/unipass

file.sendxml.dir=/send
file.xmlreceive.dir=/receive
file.xmlbackup.dir=C:/Users/KPMG/git/ap-drwb/src/main/webapp/WEB-INF/viewResources/unipass/backup