
### 시스템기본설정
#운영환경 이관시 변경 필요 
application.path = C:\dev\eclipse-jee-2023-12-R-win32-x86_64\workspace\KDB5\src\main\webapp
application.context.charset = utf-8
application.context.language = KOR
application.file.encoding = utf-8
application.level = O
application.time.nation = KOR
system.gc.rate = 85.5

### EAI Setting
eai.call.address = 10.135.106.184:6001


### JCO Connection 관련 기본설정
jco.pool.max=50
jco.conection.max=100
jco.time.out=10000
jco.wait.time=30000
max.fetch.limit=10000


### Sap Connection Config
use.client.name=TQA
# 600 client information(DEV)
TST.client=310
TST.userid=KR.KPMG01
TST.password=DJFAKsk1
TST.language=KO
TST.hostname=192.168.252.104
TST.system.number=00
# 600 client information(QA)
TQA.client=950
TQA.userid=kr.kpmg01
TQA.password=DJFAKsk1
TQA.language=KO
TQA.hostname=192.168.252.99
TQA.system.number=00
# PRD client information(RUN)
TSP.client=100
TSP.userid=kr.kpmg01
TSP.password=DJFAKsk1
TSP.language=KO
TSP.hostname=192.168.252.103
TSP.system.number=00






#엑셀 다운로드시 시트당 최대 Row
biz.excel.max.rows=50000
biz.excel.sheet.rows=30000


#최대 파일업로드 사이즈 (10M)

file.max.upload.size = 10000000
file.max.memory.size = 10000000

# 한번에 처리할 베치 데이터 사이즈 
db.batch.size=5000

# 배치작업 설정시 반드시 서버 아이피를 설정해야합니다. (여러개 지정시 곰마(,)로 구분하여 다 건 입력
# Be sure to set the server IP when setting up the batch job.
#batch.running.serverIP = 10.200.234.58
batch.running.serverIP = 10.200.12.62
# batch.running.yn 값이 Y인경우에만 Quartz Job이 수행됩니다.
batch.running.yn = N


batch.worker.name = D.Cat
batch.log.path=/logs/




# 잔량사용시 이력정보 관리 (사용 Y / 사용안함 N ) ##############################################
#
# drwbak.rawmtrl.use.log        관세환급 잔량 사용 로그      
# drwbak.rawmtrl.return.log     관세환급 잔량 반환 로그
# ctrm.rawmtrl.use.log          분증/기납증 잔량 사용 로그
# ctrm.rawmtrl.return.log       분증/기납증 자냥 반환 로그
#
################################################################################################
drwbak.rawmtrl.use.log = Y
drwbak.rawmtrl.return.log = N
ctrm.rawmtrl.use.log = Y
ctrm.rawmtrl.return.log = Y