#STG System
#jasper report file dir setting for <STG> system ( Please apped a slash(/) to the end of the path.) 
thirdparty.print.jasper.dir = /data/was-app/drwb/ROOT/WEB-INF/viewFolder/print/jasper/
#파일 업로드 기본 디렉토리
file.common.dir = /upload/
#파일 업로드 시 임시저장되는 디렉토리
file.upload.temp.dir = /upload/temp
