#Local System
#jasper report file dir setting for local system ( Please apped a slash(/) to the end of the path.) 
#thirdparty.print.jasper.dir = /data/was-app/drwb/ROOT/WEB-INF/viewFolder/print/jasper/
thirdparty.print.jasper.dir = C:/Users/KPMG/git/ap-drwb/src/main/webapp/WEB-INF/viewFolder/print/jasper/
#File upload Defaul dir
file.common.dir = /upload/
#File upload temp Dir
file.upload.temp.dir = /upload/temp
