# 생성할 tomcat 서비스와 폴더 생성에 사용할 이름입니다.
webapp.name=drwb
# tomcat 서버의 http 서비스가 제공되는 포트 번호입니다. 9080/9090/9100의 순으로 넘버링하여 사용합니다.
webapp.port=9080
# tomcat 서버가 기동될 때 지정되는 shutdown 포트 번호입니다. 9005/9006/9007의 순으로 넘버링하여 사용합니다.
webapp.shutdown_port=8005
# 배포할 어플리케이션의 war 파일 이름입니다.
# .war 확장자는 생략합니다.
webapp.artifact_name=ap-drwb-1.0.0