spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

jasypt.encryptor.bean=jasyptEncryptorAES
spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:postgresql://10.200.67.5:5432/tsfta
#ENC(55fbf4833357f761e058352adfafd1318241b3e5d24d8c05285e6a2334137927)
spring.datasource.hikari.username=kr-adm-inkyumkim
spring.datasource.hikari.password=i<CT{si#xp(~h4UTr2gArcUFJY1v3S?<!
spring.datasource.hikari.connection-test-query=SELECT 1

spring.transaction.default-timeout=108000

mybatis.configuration.map-underscore-to-camel-case=true

spring.mvc.view.prefix=/WEB-INF/viewFolder/
spring.mvc.view.suffix=.jsp

spring.main.allow-bean-definition-overriding=true

logging.level.root=debug

#EAI Call Url Prefix(DEV)
eai.call.url=http://internal-CTSTG-EAI-PRV-ALB-1416960055.ap-northeast-2.elb.amazonaws.com:5550

#Custom Error Page
server.error.path= /common/error500

#tmp File path
temp.upload.path=/data/temp

#XXS Filter excludePattern
lucy.xxs.excludePattern=/refundbasis/uploadImportExcelProcess,/refundbasis/uploadExportExcelProcess,/common/unipassReceiveData,/common/unipassRecvSync


#Cookie Setting
server.servlet.session.cookie.same-site=Strict
server.servlet.session.cookie.secure=true

#==============================================================================
# 자가생산과 부품의 자산구분 설정('??', '??' 같은 형식으로 작성할 것)
#  - biz.product.assets.type : 자가생산품 자산구분 
#  - biz.part.assets.type : 투입원재료 자산구분
#==============================================================================
biz.product.assets.type='P'
biz.part.assets.type='R'