/*
TRUNCATE TABLE INCME_LOCAL_BNT_SM;
TRUNCATE TABLE INCME_LOCAL_BNT_HSTRY;
TRUNCATE TABLE drwbak_reqstdoc_cmmn;
TRUNCATE TABLE drwbak_reqstdoc_trget_thng;
TRUNCATE TABLE drwbak_reqstdoc_incme_rawmtrl;
TRUNCATE TABLE EXPORT_CONFIRM_REASON;
UPDATE EXPORT_CERT_MST A
  SET A.ABLE_ITEM_QTY = A.ITEM_QTY
      ,A.USED_ITEM_QTY = NULL;
*/

/*
SELECT * FROM INCME_LOCAL_BNT_HSTRY
*/

INSERT INTO  INCME_LOCAL_BNT_SM
SELECT A.COMPANY_CODE
       ,A.DIVISION_CODE
       ,A.IMPDEC_MANAGE_NO
       ,B.LNE_NO
       ,B.POUCH_NO
       ,A.ACPT_DATE
       ,TRIM(B.ITEM_CODE)
       ,B.HS_CODE
       ,SUBSTR(A.ACPT_DATE, 1,6)
       ,A.ACPT_DATE
       ,NULL
       ,CASE /* 1드럼(DR) = 30KG/1 LB = 0.453592 KG/1MT = 1000KG/1M =100CM/1GR = 0.064799 G*/
             WHEN B.BASS_UNIT = 'KG' THEN B.QY * 1000                   
             WHEN B.BASS_UNIT = 'LB' THEN B.QY * 0.453592 * 1000
             WHEN B.BASS_UNIT = 'DR' THEN B.QY * 1000 * 30
             WHEN B.BASS_UNIT = 'GR' THEN B.QY * 0.064799
             WHEN B.BASS_UNIT = 'MT' THEN B.QY * 1000 * 1000
             ELSE B.QY
         END AS QY
        ,CASE WHEN B.BASS_UNIT IN ('KG','LB','DR','GR','MT') THEN 'G'
             ELSE B.BASS_UNIT
         END AS BASS_UNIT
       ,B.INCME_TARRATE
       ,B.CSTMS
       ,B.CSTMS/(CASE WHEN B.BASS_UNIT = 'KG' THEN B.QY * 1000
                       WHEN B.BASS_UNIT = 'LB' THEN B.QY * 0.453592 * 1000
                       WHEN B.BASS_UNIT = 'DR' THEN B.QY * 1000 * 30
                       WHEN B.BASS_UNIT = 'GR' THEN B.QY * 0.064799
                       WHEN B.BASS_UNIT = 'MT' THEN B.QY * 1000 * 1000
                       ELSE B.QY
                   END) AS CSTMS_AMOUNT
       ,1 AS CSTMS_AMOUNT_UNIT
       ,'KRW' AS AMOUNT_CRNCY
       ,0 AS DLIVY_QY
       ,CASE WHEN B.BASS_UNIT = 'KG' THEN B.QY * 1000
             WHEN B.BASS_UNIT = 'LB' THEN B.QY * 0.453592 * 1000
             WHEN B.BASS_UNIT = 'DR' THEN B.QY * 1000 * 30
             WHEN B.BASS_UNIT = 'GR' THEN B.QY * 0.064799
             WHEN B.BASS_UNIT = 'MT' THEN B.QY * 1000 * 1000
             ELSE B.QY
         END AS REMNDR_QY -- 최초에는 원래 수량 
       ,'00' AS RAWMTRL_SE
       ,NULL AS BKRECKN_MT
       ,'Y' AS DCSN_ENNC
       ,NULL AS LAST_USE_YYYYMMDD
       ,0 AS INTTAX
       ,0 AS ECX_AMOUNT
       ,0 AS AGSPT
       ,0 AS TRANTAX
       ,0 AS LQTX_AMOUNT
       ,A.OVSEA_SUPLER_NATION_CODE
       ,A.OVSEA_SUPLER_SMBOL AS VENDOR_CODE
       ,B.ITEM_NM
       ,A.SUPLER_MTLTY_1 AS VENDOR_NAME
       ,B.BASS_UNIT
  FROM IMPDEC_CERFIN_HDER A
 INNER JOIN  IMPDEC_CERFIN_ITEM B
   ON A.COMPANY_CODE = B.COMPANY_CODE
  AND A.DIVISION_CODE = B.DIVISION_CODE
  AND A.IMPDEC_MANAGE_NO = B.IMPDEC_MANAGE_NO
WHERE A.COMPANY_CODE = '1000'
 AND A.ACPT_DATE IS NOT NULL
;